image: "ruby:2.4.1"

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

stages:
  - checks

checks:
  stage: checks
  tags:
  - docker
  - ruby
  script:
  - gem install bundler-audit
  - bundle-audit update
  - bundle-audit check
  - bundle exec rspec
